version: '2'
services:
    log_work-mongodb:
        image: mongo:3.4.10
        ports:
            - "27017:27017"
        command: mongos --configdb log_work-mongodb-config
    log_work-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    log_work-mongodb-config:
        image: mongo:3.4.10
        container_name: log_work-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
